Contact_form
GrebilCruz/Portfolio pull request #4
Opened 2022-03-28 20:17 UTC by GrebilCruz

Made a contact form, with style of figma, added text inputs, and textareas, name with characters of 30, and comments with 500 max chars, also the email input only aceepts emails in the field, added formspree in collect data
style and colors

2022-03-29 15:58 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @GrebilCruz and @Dredwell👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-29 15:58 UTC, thecodechaser commented on home.html
> +    </form>
- [ ] The form is not supposed to be submitted if one or more fields is empty, please add the `required` attribute in all of your form fields. It will prevent the form to be submitted if one or more of the fields is empty.

2022-03-29 15:58 UTC, thecodechaser commented on home.html
> +    <h3>If you have an application you are interested in developing, a feature that you need built or a project that needs coding. I’d love to help with it </h3>
- [ ] Great job on the design, but for this project you are supposed to stick to the [Figma ](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1)template as much as possible. Please reduce the background images size and make sure it matches the design on the template.

### Your design

![image](https://user-images.githubusercontent.com/83803414/160653448-16ad349d-661f-4121-b829-b247c5d2b13d.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/160653551-ebb01bb2-7d3c-413a-a8ee-932831e7b22d.png)

2022-03-29 15:58 UTC, thecodechaser commented on style.css
> +}
- [ ] Please increase the padding of input fields a little, add property `border: none `, and make sure it matches the design on the template.

### Your design

![image](https://user-images.githubusercontent.com/83803414/160654193-a2f19402-7f9e-456f-89d5-82d18eea83cc.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/160654025-9743a192-89c9-4507-b8db-bbf9abc9a822.png)

2022-03-30 04:45 UTC, phelian23 approved these changes
Hi @GrebilCruz, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-30 04:45 UTC, phelian23 commented on home.html
> +        </div>
- [ ] [Optional] Kindly implement button interactions to the contact-form button
![Capture](https://user-images.githubusercontent.com/85095702/160753020-02303e61-a865-4175-8532-3b830eb8da77.PNG)

2022-03-30 05:03 UTC, merged